export const ProjectData = [
  {
    id: 1,
    title: "Amazon Clone",
    link: "https://amazon-clone-swart-ten.vercel.app/",
    image: "/images/amazon.webp",
    reverse: false,
    latest: true,
  },
  {
    id: 2,
    title: "Netflix Clone",
    link: "https://love-sonkar.github.io/Netflix/",
    image: "/images/netflix.webp",
    reverse: true,
    latest: true,
  },
  {
    id: 3,
    title: "Tic tac toa Clone",
    link: "https://love-sonkar.github.io/tictactoe/",
    image: "/images/tictactoe.webp",
    reverse: false,
    latest: false,
  },
  {
    id: 4,
    title: "Microsoft Clone",
    link: "https://love-sonkar.github.io/microsoft-webclone/",
    image: "/images/microsoft.webp",
    reverse: true,
    latest: true,
  },
  {
    id: 5,
    title: "OneVision HealthCare",
    link: "https://love-sonkar.github.io/One-Vision-Healthcare/",
    image: "/images/onevision.webp",
    reverse: false,
    latest: false,
  },
  {
    id: 6,
    title: "Meshop Online Shopping App",
    link: "https://love-sonkar.github.io/MeShop/",
    image: "/images/meshop.webp",
    reverse: true,
    latest: false,
  },
  {
    id: 7,
    title: "WorldClock",
    link: "https://love-sonkar.github.io/WorldClock/",
    image: "/images/worldclock.webp",
    reverse: false,
    latest: false,
  },
];
